//
//  Nations.swift
//  TableSample
//
//  Created by Kiyong Kim on 2017. 8. 21..
//  Copyright © 2017년 KPU ios app dev. All rights reserved.
//

import Foundation

struct Nations {
    static let contintents: [(region:String, countries:[(name:String, file:String)])] = [
        (region:"Africa, Middle East, and India",
         countries:[(name:"Armenia", file:"armenia.png"),
                    (name:"Botswana", file:"botswana.png"),
                    (name:"Bahrain", file:"bahrain.png"),
                    (name:"Cameroun", file:"cameroon.png"),
                    (name:"Centre Afrique", file:"central_african_republic.png"),
                    (name:"Côte d'Ivoire", file:"cotedivoire.png"),
                    (name:"Egypt", file:"egypt.png"),
                    (name:"Guinea-Bissau", file:"guinea_bisseau.png"),
                    (name:"Guinée", file:"guinea.png"),
                    (name:"Guinée Equatoriale", file:"equatorial_guinea.png"),
                    (name:"India", file:"india.png"),
                    (name:"Israel", file:"israel.png"),
                    (name:"Jordan", file:"jordan.png"),
                    (name:"Kenya", file:"kenya.png"),
                    (name:"Kuwait", file:"kuwait.png"),
                    (name:"Madagascar", file:"madagascar.png"),
                    (name:"Mali", file:"mali.png"),
                    (name:"Maroc", file:"morocco.png"),
                    (name:"Mauritius", file:"mauritius.png"),
                    (name:"Mozambique", file:"mozambique.png"),
                    (name:"Niger", file:"niger.png"),
                    (name:"Nigeria", file:"nigeria.png"),
                    (name:"Oman", file:"oman.png"),
                    (name:"Qatar", file:"qatar.png"),
                    (name:"Saudi Arabia", file:"saudi_arabia.png"),
                    (name:"Sénégal", file:"senegal.png"),
                    (name:"South Africa", file:"south_africa.png"),
                    (name:"Tunisie", file:"tunisia.png"),
                    (name:"Uganda", file:"uganda.png"),
                    (name:"United Arab Emirates", file:"united_arab_emirates.png"),
                    ]),
        (region:"Asia Pacific",
         countries:[(name:"Australia", file:"australia.png"),
                    (name:"中国", file:"china.png"),
                    (name:"Hong Kong (English)", file:"hong_kong.png"),
                    (name:"香港", file:"hong_kong.png"),
                    (name:"Indonesia", file:"indonesia.png"),
                    (name:"日本", file:"japan.png"),
                    (name:"대한민국", file:"south_korea.png"),
                    (name:"Malaysia", file:"malaysia.png"),
                    (name:"New Zealand", file:"new_zealand.png"),
                    (name:"Philippines", file:"philippines.png"),
                    (name:"Singapore", file:"singapore.png"),
                    (name:"台灣", file:"taiwan.png"),
                    (name:"Thailand", file:"thailand.png"),
                    (name:"Vietnam", file:"vietnam.png"),
                    (name:"Other Asia", file:"generic.png"),
                    ]),
        (region:"Europe",
         countries:[(name:"België", file:"belgium.png"),
                    (name:"Belgique", file:"belgium.png"),
                    (name:"България", file:"bulgaria.png"),
                    (name:"Česká republika", file:"czech_republic.png"),
                    (name:"Danmark", file:"denmark.png"),
                    (name:"Deutschland", file:"germany.png"),
                    (name:"Eesti", file:"estonia.png"),
                    (name:"España", file:"spain.png"),
                    (name:"France", file:"france.png"),
                    (name:"Greece", file:"greece.png"),
                    (name:"Hrvatska", file:"croatia.png"),
                    (name:"Ireland", file:"ireland.png"),
                    (name:"Italia", file:"italy.png"),
                    (name:"Latvija", file:"latvia.png"),
                    (name:"Liechtenstein", file:"liechtenstein.png"),
                    (name:"Lietuva", file:"lithuania.png"),
                    (name:"Luxembourg", file:"luxembourg.png"),
                    (name:"Macedonia", file:"macedonia.png"),
                    (name:"Magyarország", file:"hungary.png"),
                    (name:"Malta", file:"malta.png"),
                    (name:"Moldova", file:"moldova.png"),
                    (name:"Montenegro", file:"montenegro.png"),
                    (name:"Nederland", file:"netherlands.png"),
                    (name:"Norge", file:"norway.png"),
                    (name:"Österreich", file:"austria.png"),
                    (name:"Polska", file:"poland.png"),
                    (name:"Portugal", file:"portugal.png"),
                    (name:"România", file:"romania.png"),
                    (name:"Россия", file:"russia.png"),
                    (name:"Slovakia", file:"slovak_republic.png"),
                    (name:"Slovenia", file:"slovenia.png"),
                    (name:"Schweiz", file:"switzerland.png"),
                    (name:"Suisse", file:"switzerland.png"),
                    (name:"Suomi", file:"finland.png"),
                    (name:"Sverige", file:"sweden.png"),
                    (name:"Türkiye", file:"turkey.png"),
                    (name:"UK", file:"uk.png"),
                    ]),
        (region:"Latin America and the Caribbean",
         countries:[(name:"Anguilla", file:"anguilla.png"),
                    (name:"Antigua & Barbuda", file:"antigua.png"),
                    (name:"Argentina", file:"argentina.png"),
                    (name:"Barbados", file:"barbados.png"),
                    (name:"Belize", file:"belize.png"),
                    (name:"Bermuda", file:"bermuda.png"),
                    (name:"Bolivia", file:"bolivia.png"),
                    (name:"Brasil", file:"brazil.png"),
                    (name:"British Virgin Islands", file:"british-virgin-islands.png"),
                    (name:"Cayman Islands", file:"cayman-islands.png"),
                    (name:"Chile", file:"chile.png"),
                    (name:"Colombia", file:"colombia.png"),
                    (name:"Costa Rica", file:"costa_rica.png"),
                    (name:"Dominica", file:"dominica.png"),
                    (name:"República Dominicana", file:"dominican_republic.png"),
                    (name:"Ecuador", file:"ecuador.png"),
                    (name:"El Salvador", file:"el_salvador.png"),
                    (name:"Grenada", file:"grenada.png"),
                    (name:"Guatemala", file:"guatemala.png"),
                    (name:"Guyana", file:"guyana.png"),
                    (name:"Honduras", file:"honduras.png"),
                    (name:"Jamaica", file:"jamaica.png"),
                    (name:"México", file:"mexico.png"),
                    (name:"Montserrat", file:"montserrat.png"),
                    (name:"Nicaragua", file:"nicaragua.png"),
                    (name:"Panamá", file:"panama.png"),
                    (name:"Paraguay", file:"paraguay.png"),
                    (name:"Perú", file:"peru.png"),
                    (name:"St. Kitts & Nevis", file:"st-kitts-nevis.png"),
                    (name:"St. Lucia", file:"st-lucia.png"),
                    (name:"St. Vincent & The Grenadines", file:"st-vincent.png"),
                    (name:"Suriname", file:"suriname.png"),
                    (name:"The Bahamas", file:"bahamas.png"),
                    (name:"Trinidad & Tobago", file:"trinidad.png"),
                    (name:"Turks & Caicos", file:"turks_caicos.png"),
                    (name:"Uruguay", file:"uruguay.png"),
                    (name:"Venezuela", file:"venezuela.png"),
                    (name:"América Latina y el Caribe (español)", file:"generic.png"),
                    (name:"Latin America and the Caribbean (English)", file:"generic.png"),
                    ]),
        (region:"The United States, Canada, and Puerto Rico", 
         countries:[(name:"Canada (English)", file:"canada.png"),
                    (name:"Canada (Français)", file:"canada.png"),
                    (name:"Puerto Rico (English)", file:"puerto_rico.png"),
                    (name:"Puerto Rico (español)", file:"puerto_rico.png"),
                    (name:"USA", file:"usa.png"),
                    ]),
        ]
}
